spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mysql://localhost:3306
    username: root
    password: 1Q2w3e4r@
    name: testdb

logging:
  level:
    org.springframework.r2dbc.core: debug;